# Generated by Django 5.1.3 on 2024-11-14 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_financiado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_inicio', models.DateField()),
                ('prazo_anos', models.IntegerField()),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financiamentos', to='imoveis.imovel')),
            ],
        ),
    ]
